# Generated by Django 4.2 on 2025-11-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultorio_API", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicamentorecetado",
            name="existencia",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="medicamentocatalogo",
            name="categoria",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="medicamentocatalogo",
            name="departamento",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="medicamentocatalogo",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="medicamentos/"),
        ),
    ]
