# Generated by Django 4.2 on 2025-11-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultorio_API", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE consultorio_API_medicamentorecetado "
                        "ADD COLUMN IF NOT EXISTS existencia integer UNSIGNED DEFAULT 0"
                    ),
                    reverse_sql=(
                        "ALTER TABLE consultorio_API_medicamentorecetado "
                        "DROP COLUMN IF EXISTS existencia"
                    ),
                )
            ],
            state_operations=[
                migrations.AddField(
                    model_name="medicamentorecetado",
                    name="existencia",
                    field=models.PositiveIntegerField(default=0),
                )
            ],
        ),
        migrations.AlterField(
            model_name="medicamentocatalogo",
            name="categoria",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="medicamentocatalogo",
            name="departamento",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="medicamentocatalogo",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="medicamentos/"),
        ),
    ]
