# Generated by Django 4.2 on 2025-07-25 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("consultorio_API", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            lambda apps, schema_editor: apps.get_model('consultorio_API', 'Antecedente')
            .objects.filter(severidad__isnull=True)
            .update(severidad='media'),
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            lambda apps, schema_editor: apps.get_model('consultorio_API', 'Antecedente')
            .objects.filter(estado_actual__isnull=True)
            .update(estado_actual='estable'),
            reverse_code=migrations.RunPython.noop,
        ),
    ]
