# Generated by Django 4.2 on 2025-08-22 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultorio_API", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicamentorecetado",
            name="existencia",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
