# Generated by Django 4.2 on 2025-11-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultorio_API", "0002_medicamentorecetado_existencia_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medicamentocatalogo",
            name="codigo_barras",
        ),
        migrations.AlterField(
            model_name="medicamentocatalogo",
            name="existencia",
            field=models.IntegerField(default=0),
        ),
    ]
