# Generated by Django 4.2 on 2025-11-24 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultorio_API", "0002_update_medicamentocatalogo_clave"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicamentorecetado",
            name="existencia",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
