# Generated by Django 4.2 on 2025-08-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultorio_API", "0002_signosvitales_registrado_por"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicamentorecetado",
            name="codigo_barras",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
