# Generated by Django 4.2 on 2025-08-20 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultorio_API", "0003_medicamentorecetado_codigo_barras_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicamentorecetado",
            name="cantidad",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
