# Generated by Django 4.2 on 2025-08-20 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultorio_API", "0003_medicamentorecetado_codigo_barras_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cita",
            name="tipo_cita",
            field=models.CharField(
                choices=[
                    ("primera_vez", "Primera Vez"),
                    ("cita_normal", "Cita Normal"),
                ],
                default="cita_normal",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="medicamentorecetado",
            name="cantidad",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
