# Generated by Django 4.2 on 2025-08-20 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultorio_API", "0004_alter_cita_tipo_cita_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicamentoCatalogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("codigo_barras", models.CharField(max_length=50, unique=True)),
                ("existencia", models.PositiveIntegerField(default=0)),
                (
                    "departamento",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "precio",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("categoria", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "imagen",
                    models.ImageField(blank=True, null=True, upload_to="catalogo/"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="medicamentorecetado",
            name="categoria",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="medicamentorecetado",
            name="departamento",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="cita",
            name="tipo_cita",
            field=models.CharField(
                choices=[
                    ("primera_vez", "Primera Vez"),
                    ("cita_normal", "Cita Normal"),
                ],
                default="cita_normal",
                max_length=20,
            ),
        ),
    ]
