# Generated by Django 4.2 on 2025-08-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "consultorio_API",
            "0005_medicamentocatalogo_medicamentorecetado_categoria_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="medicamentorecetado",
            name="existencia",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="medicamentorecetado",
            name="precio",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
