# Generated by Django 4.2 on 2025-08-21 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "consultorio_API",
            "0005_medicamentocatalogo_medicamentorecetado_categoria_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medicamentocatalogo",
            name="categoria",
        ),
        migrations.RemoveField(
            model_name="medicamentocatalogo",
            name="departamento",
        ),
        migrations.RemoveField(
            model_name="medicamentocatalogo",
            name="existencia",
        ),
        migrations.RemoveField(
            model_name="medicamentocatalogo",
            name="imagen",
        ),
        migrations.RemoveField(
            model_name="medicamentocatalogo",
            name="precio",
        ),
        migrations.AddField(
            model_name="medicamentocatalogo",
            name="clave",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="medicamentocatalogo",
            name="imagen_url",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="medicamentocatalogo",
            name="presentacion",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
